In [5]:
# Dependencies
import pandas as pd

In [13]:
# File to load
file_one = "Pokemon.csv"

In [15]:
# Read with Pandas
pke_df = pd.read_csv(file_one)

In [20]:
# Extract the following columns: 
column_df = pke_df.loc[:,["Type 1", "HP", "Attack", "Sp. Atk", "Sp. Def", "Speed"]]

In [28]:
# Create a dataframe of the average stats for each type of pokemon.
Aver_statedf = column_df.groupby(['Type 1']).mean()

In [35]:
# Calculate the total power level of each type of pokemon by adding all of the stats together.
# Place the results into a new column.

Aver_statedf["Total"] = Aver_statedf.sum(axis=1)
Aver_statedf

                 HP      Attack    Sp. Atk    Sp. Def       Speed       Total
Type 1
Bug       56.884058   70.971014  53.869565  64.797101   61.681159  308.202899
Dark      66.806452   88.387097  74.645161  69.516129   76.161290  375.516129
Dragon    83.312500  112.125000  96.843750  88.843750   83.031250  464.156250
Electric  59.795455   69.090909  90.022727  73.704545   84.500000  377.113636
Fairy     74.117647   61.529412  78.529412  84.705882   48.588235  347.470588
Fighting  69.851852   96.777778  53.111111  64.703704   66.074074  350.518519
Fire      69.903846   84.769231  88.980769  72.211538   74.442308  390.307692
Flying    70.750000   78.750000  94.250000  72.500000  102.500000  418.750000
Ghost     64.437500   73.781250  79.343750  76.468750   64.343750  358.375000
Grass     67.271429   73.214286  77.500000  70.428571   61.928571  350.342857
Ground    73.781250   95.750000  56.468750  62.750000   63.906250  352.656250
Ice       72.000000   72.750000  77.541667  76.291667   63.458333  362.041667
Normal    77.275510   73.469388  55.816327  63.724490   71.551020  341.836735
Poison    67.250000   74.678571  60.428571  64.392857   63.571429  330.321429
Psychic   70.631579   71.456140  98.403509  86.280702   81.491228  408.263158
Rock      65.363636   92.863636  63.340909  75.477273   55.909091  352.954545
Steel     65.222222   92.703704  67.518519  80.629630   55.259259  361.333333
Water     72.062500   74.151786  74.812500  70.517857   65.964286  357.508929

In [38]:
# Bonus: Sort the table by strongest type and export the resulting table to a new CSV.
Total_rankingsdf = Aver_statedf.sort_values('Total', ascending=False)
Total_rankingsdf.to_csv("pokemon_rankings.csv")